#!/usr/bin/with-contenv bash

if [ -f "/golang.tar.gz" ]; then
  echo "Installing golang"
  tar -C /usr/local -xzf /golang.tar.gz
  rm /golang.tar.gz
else
  echo "golang already installed, skipping"
fi

echo "ensuring golang is in PATH"
if grep -q '^PATH=' /etc/services.d/code-server/run; then
  if ! grep -q '^PATH=.*/usr/local/go/bin.*' /etc/services.d/code-server/run; then
    sed -i '/PATH/ s/$/:\/usr\/local\/go\/bin/' /etc/services.d/code-server/run
  fi
else
  sed -i '/^#!\/usr\/bin/a \\n# Added by codeserver-golang\nPATH=$PATH:/usr/local/go/bin' /etc/services.d/code-server/run
fi