#!/usr/bin/with-contenv bash

if [ -f "/golang.tar.gz" ]; then
  echo "Installing golang"
  tar -C /usr/local -xzf /golang.tar.gz
  rm /golang.tar.gz
else
  echo "golang already installed, skipping"
fi
